### ISSUE TITLE
Compatibility with aws-sdk v3

### ISSUE THREAD

**Issue by motawy** [shelfio/jest-dynamodb#102]
Does this work with the release of the v3 of aws-sdk? 

I keep receiving connection errors after the update. Is this compatible with the major of aws-sdk or still in the works? 

Specifically that's the error:
```
Error: AWS SDK error wrapper for Error: connect ECONNREFUSED 127.0.0.1:80
```
Which is weird considering the port for the local tests is 8000. 

The connection details is as per suggestions from the Jest website.

**Comment by panchogbcu** [comment]
Did you try using a valid AWS `region`, fake `credentials` and `tls` set to `false`?
```ts
const dynamoDbClient = new DynamoDBClient({
  endpoint: 'http://127.0.0.1:8000',
  region: 'eu-central-1',
  tls: false,
  credentials: {
    accessKeyId: 'foo',
    secretAccessKey: 'bar',
  },
});
```

**Comment by motawy** [comment]
It appears to be working now for some reason. I might have not inserted the option of `tls: false`. 

Thanks for reply!

**Comment by sho-ai-main** [comment]
@panchogbcu thanks for your comment, I had the same issue and it was fixed by changing to a real AWS region, shouldn't we update the docs to put in a real region instead of the current 'local-env' region? Is it supposed to work with a fake region? I can open a pull request to change the docs if needed.
