### ISSUE TITLE
Connection refused after retesting.

### ISSUE THREAD

**Issue by anothersaddeveloper** [shelfio/jest-dynamodb#58]
Hello, 
If I run my tests with the --watchAll flag the first time it runs just fine, but if I try to rerun using one of the watch commands it will output CONNECTION refused after a while.
What I think is happening is that the DynamoDB instance isn't persisting after first test run,
 is there any way to preserve the watch flag and rerun tests with them making a new instance of dynamo?
![Screenshot 2019-09-16 at 13 02 53](https://user-images.githubusercontent.com/54319681/64956416-731ae000-d882-11e9-9e6c-d3d3d3547903.png)

**Comment by freshollie** [comment]
It's related to this: https://github.com/facebook/jest/issues/6800

**Comment by freshollie** [comment]
@anothersaddeveloper I have rewritten this library to be lighter and fix this usecase, please check it out: https://github.com/freshollie/jest-dynalite

**Comment by Keksike** [comment]
I'm also running into this issue, and I dont have any globalSetup or globalTeardown currently. Here is my setup:

https://gist.github.com/Keksike/da2e2de048e85468f84fbc4b719b0d5c

**Comment by scottybrown** [comment]
I found that it's because this library uses dynamodb-local, which keeps a list of `runningProcesses` keyed on port.
Since this library's `teardown.js` calls `DynamoDbLocal.stopChild` rather than `DynamoDbLocal.stop`, `runningProcesses` doesn't get updated. So the next time the setup runs it thinks Dynamo is already running and doesn't start it.
Can fix it with a jest globalTeardown that runs `await DynamoDbLocal.stop(8000);` (or whatever port you're using), but that's making an assumption about the internals of this library which is no good.
Probably, `jest-dynalite` is the answer :)
